### ISSUE TITLE
[Bug] hCaptcha not working only for some?

### ISSUE THREAD

**Issue by v6r** [GooseMod/OpenAsar#57] opened 2022-05-01 19:22 UTC
New accounts need captcha for dm or server join
With the new asar i cant click on the captcha/it doesnt do anything if you click on it
With the normal one i can

![image](https://user-images.githubusercontent.com/83277314/166161300-5d49c679-efb4-4a48-b760-6134ac9086d6.png)

**Comment by CanadaHonk** [comment] 2022-05-01 19:25
You are sure this is OpenAsar only and the vanilla asar works fine? Hasn't been reported by anyone else and cannot reproduce.

**Comment by zachjmurphy** [comment] 2022-05-01 21:12
I have had the same bug when trying to add a bot to a server through the "Add to Server" button on bot profiles.

**Comment by hax4dazy** [comment] 2022-05-01 21:17
Just tested it on my client and it works with both GM + OA installed

**Comment by zachjmurphy** [comment] 2022-05-01 21:22
> Just tested it on my client and it works with both GM + OA installed

Did you test where I was having the issue?

> I had the same bug when trying to add a bot to a server through the "Add to Server" button on bot profiles.

**Comment by hax4dazy** [comment] 2022-05-01 21:43
> Did you test where I was having the issue?
Yeah, specifically added a discord bot to a server using the method that you described and everything worked fine

**Comment by zachjmurphy** [comment] 2022-05-01 22:13
> Did you test where I was having the issue?
> Yeah, specifically added a discord bot to a server using the method that you described and everything worked fine

Weird okay. Because it never seems to work for me. The captcha appears but then it disappears.

**Comment by 7v2p** [comment] 2022-05-09 19:55
same issue captcha keep disappears

**Comment by CanadaHonk** [comment] 2022-05-20 21:31
Can y'all please confirm quickstart on/off and if you still have or had the issue?

**Comment by v6r** [comment] 2022-05-20 21:45
> Can y'all please confirm quickstart on/off and if you still have or had the issue?

same problem with and without quicksart

**Comment by CanadaHonk** [comment] 2022-06-25 10:56
Might have been possibly fixed in last commit, do you still have the issue?

**Comment by CanadaHonk** [comment] 2022-09-18 11:10
Closing due to inactivity

**Closed by CanadaHonk** 2022-09-18 11:10 UTC
Labels: bug

**Comment by SammCheese** [comment] 2022-10-05 06:52
Can confirm this.
